# ---- Build Stage ----
FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /app

# Copy pom.xml and download dependencies first (cache)
COPY pom.xml .
RUN mvn -B dependency:go-offline

# Copy source code and build project
COPY src ./src
RUN mvn -B clean package -DskipTests

# ---- Run Stage ----
FROM eclipse-temurin:21-jre

WORKDIR /app

# Copy the built jar from previous stage
COPY --from=build /app/target/vediocall-0.0.1-SNAPSHOT.jar app.jar

# Render provides PORT env automatically
#ENV PORT=8080

EXPOSE 8080

# Run the app
CMD ["java", "-jar", "app.jar"]
